### GET request to example server
POST http://localhost:8081/deploy
Content-Type: application/json

{
  "name" : "test",
  "env": {
    "TEST": "1"
  },
  "source" : {
    "name" : "test.mjs",
    "mime" : null,
    "file" : null,
    "language" : "js",
    "type" : "string",
    "data" : "export function handleRequest(request) {request.response().end(`${env.DEPLOYMENT_NAME} is now running on ${env.RUNTIME} with TEST = ${env.TEST}`);\n}\n"
  }
}
###

GET test.localhost:8080
